### PR TITLE
bugfix dscl provider

### LINKED ISSUE #2667: UID already exists when setting the UID option for user on Mac OS
We are working on managing our local Mac OS clients with Chef like all of our other servers. If we do not use the option "uid" everything proceeds as it should. As soon as we define the UID option we are told that UID is already in use. We have verified that is not the case before the chef run. However after the chef run the UID is updated in DSCL like we would want it to be.

================================================================================
Error executing action `create` on resource 'user[test]'
===============================================================================
    Chef::Exceptions::RequestedUIDUnavailable
    -----------------------------------------
    uid 510 is already in use

    Resource Declaration:
    ---------------------
           # In /tmp/kitchen/cache/cookbooks/local-users/recipes/default.rb

            64:   user("test") do
            65:     password "BLAH BLAH BLAH"
            66:     salt "BLAH BLAH BLAH"
            67:     iterations 25000
            68:     shell "/bin/bash"
            69:     uid 510
            70:     gid 601
            71:     home "/Users/test"
            72:     supports  :manage_home => true
            73:   end
            74:

    Compiled Resource:
    ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/local-users/recipes/default.rb:64:in `block in from_file'

           user("test") do
             action :create
             supports {:manage_home=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             username "test"
             uid 510
             gid 601
             home "/Users/test"
             shell "/bin/bash"
             password "BLAH BLAH BLAH"
             iterations 25000
             salt "BLAH BLAH BLAH"
             declared_type :user
             cookbook_name "local-users"
             recipe_name "default"
           end

       [2014-12-16T14:00:07-08:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
       [2014-12-16T14:00:07-08:00] ERROR: Running exception handlers
       Running handlers complete

       [2014-12-16T14:00:07-08:00] ERROR: Exception handlers complete
       [2014-12-16T14:00:07-08:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
Chef Client failed. 1 resources updated in 5.877127 seconds
       [2014-12-16T14:00:07-08:00] ERROR: user[test] (local-users::default line 64) had an error: Chef::Exceptions::RequestedUIDUnavailable: uid 510 is already in use
       [2014-12-16T14:00:08-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

### PR DESCRIPTION
**Pull request by patcox**
We need to compare with the UID, not a GUID. So we need to map the
correct field for comparison.

Also fix a bug in determining used uids.

This fixes this exception when the specified uid is actually in use by the
correct user:

    Chef::Exceptions::RequestedUIDUnavailable: uid 48 is already in use

This resolves #2667.
@jaymzh will do the merge so it falls under his CCLA.

### CODE REVIEW

**Comment by jaymzh** [comment]
@patcox you have failing tests.

**Comment by patcox** [comment]
I'll check out the failing tests. I had some weird behavior when running the tests locally, so I wanted to create the PR to see what CI said.

**Comment by patcox** [comment]
@jaymzh - tests are fixed and passing.

**Comment by jaymzh** [comment]
Wow, the tests imply that GeneratedUID wasn't a typo, but they intended that... but clearly it doesn't work.

@sersut, @jtimberman, - what say you?

File: lib/chef/provider/user/dscl.rb [hunk 1]
```diff
@@ -239,8 +239,16 @@ def get_free_uid(search_limit=1000)
...
+          users_uids = run_dscl("list /Users uid").split("\n")
+          uid_map = users_uids.inject({}) do |tmap, tuid|
+            x = tuid.split
+            tmap[x[1]] = x[0]
+            tmap
+          end
+          if uid_map[uid.to_s]
+            return true unless uid_map[uid.to_s] == @new_resource.username.to_s
+          end
+          return false
```
Comment (jtimberman) [inline lib/chef/provider/user/dscl.rb]: This is awkward to read, because we get into a conditional that returns true... unless the uid matches the provided username. I think it would be cleaner to use implicit return.

**Comment by jtimberman** [comment]
Seems fine to me, but we could be more expressive w/ the conditional and returns as I commented.

File: lib/chef/provider/user/dscl.rb (hunk 1 above)
Comment (jaymzh) [inline lib/chef/provider/user/dscl.rb]: So what is it you're looking for? This?

```
uid_map[uid.to_s] && uid_map[uid.to_s] != @new_resource.username.to_s
```
?

I think that's far less clear. How about:

```
if uid_map[uid.to_s]
  unless uid_map[uid.to_s] == @new_resource.username.to_s
    return true
  end
end
false
```

**Comment by jaymzh** [comment]
@jtimberman ?

File: lib/chef/provider/user/dscl.rb (hunk 1 above)
Comment (jtimberman) [inline lib/chef/provider/user/dscl.rb]: I think the second one is probably better. It reads cleaner than the diff.

**Comment by jaymzh** [comment]
Paging @sersut

**Comment by jtimberman** [comment]
:+1:

**Comment by sersut** [comment]
Sweet :+1:

**Comment by jaymzh** [comment]
OK, cool. :+1:

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @patcox

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)
