### PR TITLE
correct filters for MacPorts package provider

### LINKED ISSUE #2691: macports provider has incorrect filters
macports currently provides `macports_package` to `os => 'mac_os_x'` but that's not an OS, it should be darwin.

### PR DESCRIPTION
**Pull request by patcox**
macports needs to provide macports_package to `darwin`, not `mac_os_x`. `mac_os_x` is the platform, `darwin` is the OS.
This resolves #2691. 
@jaymzh will do the merge so it's under his CCLA.

### CODE REVIEW

**Comment by jaymzh** [comment]
@patcox you need to sort out your failed tests.
@opscode/client-core as Pat said, I'll do the merge since I'm the FB person with CCLA, but I want someone with OSX specific knowledge to look at this, #2722, #2723, and #2724 - probably @jtimberman ?

File: lib/chef/provider/package/macports.rb [hunk 1]
```diff
@@ -3,7 +3,7 @@ class Provider
     class Package
       class Macports < Chef::Provider::Package
 
-        provides :macports_package, os: "mac_os_x"
+        provides :macports_package, os: "darwin"
```
Comment (jaymzh) [inline lib/chef/provider/package/macports.rb]: this should probably have no filters... if someone actually specified `macports_package`, then they are overriding the normal logic. That seems to be how the other OS-specific providers with their own resource work... (like homebrew_package)

Comment (lamont-granquist) [inline lib/chef/provider/package/macports.rb]: Yeah, but does it make any sense on linux/solaris/freebsd/etc?  Ultimately, it'd be nice to unload these classes that didn't apply to the o/s to reduce memory pressure.

Comment (patcox) [inline lib/chef/provider/package/macports.rb]: I could see arguments either way.
For consistency's sake maybe it would be best to remove the filters. (see homebrew @ https://github.com/opscode/chef/blob/master/lib/chef/provider/package/homebrew.rb#L29)
And then if we want to unload the classes later we could do that in a separate PR.

Comment (lamont-granquist) [inline lib/chef/provider/package/macports.rb]: I sort of feel like we should be more narrow and then expand later if there's a reason, rather than try to do it the other direction since its avoids a possible major revision blocker to the later change.

Comment (jaymzh) [inline lib/chef/provider/package/macports.rb]: My thought is more like this... I *can* make apt work on Redhat, and I *can* make yum work on Debian, etc. if someone goes out of their way to specifically say "I want to use macports_package", we shouldn't stand in their way. We should just never use macports for standard `package` resource on a host we don't expect it to work on.

Comment (lamont-granquist) [inline lib/chef/provider/package/macports.rb]: Hmmmm....  okay, I seem to have not restricted yum_package, apt_package, etc, so I guess I agreed with you back when I merged in the provider resolver stuff (although I coulda sworn I decided to do the other thing).

**Comment by patcox** [comment]
Added a new commit removing the filter altogether, as discussed in code review.
I'm not sure why those tests were failing...if they fail again, I could use some help figuring out how to fix them.

**Comment by jaymzh** [comment]
Well, the test that's failing is "1) Chef::ProviderResolver resolving static providers on Ubuntu 14.04 when the resource is a macports_package should fall back into the old provider mapper code and hooks", except that test is now invalid... it's unclear what @lamont-granquist  would like ot happen to this test.

**Comment by lamont-granquist** [comment]
It should get removed from that one because it not longer falls through to the old provider mapper code, and now it uses the provider resolver correctly, so i think there's another list it gets added to.

File: spec/unit/provider_resolver_spec.rb [hunk 2]
```diff
@@ -511,10 +511,11 @@ def resource_class(resource)
...
         :apt_package, :bash, :breakpoint, :chef_gem, :cookbook_file, :csh, :deploy,
-        :deploy_revision, :directory, :dpkg_package, :easy_install_package,
-        :erl_call, :execute, :file, :gem_package, :git, :http_request, :link, :log, :pacman_package, :paludis_package,
-        :perl, :python, :remote_directory, :route, :rpm_package, :ruby, :ruby_block, :script,
-        :subversion, :template, :timestamped_deploy, :whyrun_safe_ruby_block, :yum_package, :homebrew_package,
+        :deploy_revision, :directory, :dpkg_package, :easy_install_package, :erl_call,
+        :execute, :file, :gem_package, :git, :homebrew_package, :http_request, :link,
+        :log, :macports_package, :pacman_package, :paludis_package, :perl, :python,
+        :remote_directory, :route, :rpm_package, :ruby, :ruby_block, :script, :subversion,
+        :template, :timestamped_deploy, :whyrun_safe_ruby_block, :yum_package,
```
Comment (patcox) [inline spec/unit/provider_resolver_spec.rb]: I moved `:homebrew_package` and `:macports_package` to their correct alphabetical order and made the lines roughly the same length.

**Comment by patcox** [comment]
Tests are green now. :)
lmk if there's anything else to fix.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by jaymzh** [comment]
:+1: 

Sweet. Lets get a 3rd +1 and I'll merge.

**Comment by lamont-granquist** [comment]
@opscode/client-core @opscode/client-engineers paging code review

**Comment by jtimberman** [comment]
:+1: :cake:

**Comment by jaymzh** [comment]
WFM.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @patcox

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)
